name: product-catalog-ci

on:
  pull_request:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: setup go 1.22
              uses: actions/setup-go@v2
              with:
                go-version: 1.22
            
            - name: build
              run: |
                cd src/product-catalog
                go mod download
                go build -o product-catalog-service main.go
            
            - name: unit tests
              run: |
                cd src/product-catalog
                go test ./...
    
    code-quality:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: run golangci-lint
              run: 
                    go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2
                    golangci-lint run src/product-catalog/...
            
    docker:
        runs-on: ubuntu-latest

        needs: build

        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: install docker
              uses: docker/setup-buildx-action@v1
            
            - name: login to docker
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: docker push
              uses: docker/build-push-action@v6
              with:
                context: src/product-catalog
                file: Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}
            
    update-k8s:
        runs-on: ubuntu-latest

        needs: docker

        steps:
            - name: checkout code
              uses: actions/checkout@v4
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
            
            - name: update tag in k8s deployment manifest
              run: |
                    sed -i 's|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}|' kubernetes/productcatalog/deploy.yaml
            
            - name: commit and push changes
              run: |
                    git config --global user.email "preetimansahoo@gmail.com"
                    git config --global user.name "preetimans"
                    git add kubernetes/productcatalog/deploy.yaml
                    git commit -m "[CI]: update product catalog image tag"
                    git push origin main
            
                